export const addButton = document.querySelector('.add-form-button')
export const nameInput = document.querySelector('.add-form-name')
export const commentInput = document.querySelector('.add-form-text')
export const commentsList = document.querySelector('.comments')
export const addForm = document.querySelector('.add-form')
export const addLoader = document.querySelector('.add-loader')
export const container = document.querySelector('.container')
